# Generated by Django 3.0.3 on 2020-03-05 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attdc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 16, 36, 48, 265743)),
        ),
    ]
