# Generated by Django 3.0.3 on 2020-03-05 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attdc', '0002_student_tod_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 16, 57, 41, 352947)),
        ),
    ]
