# Generated by Django 3.0.3 on 2020-03-05 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attdc', '0003_auto_20200305_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 17, 13, 57, 840175)),
        ),
    ]
