# Generated by Django 3.0.3 on 2020-03-08 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attdc', '0066_auto_20200308_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 23, 21, 21, 216743)),
        ),
    ]
